module.exports = {
  ActionTypes: {
    FETCH_PLAYLISTS: 'FETCH_PLAYLISTS',
    FETCH_PLAYLIST: 'FETCH_PLAYLIST',
    FETCH_TRACK: 'FETCH_TRACK',
    UPDATE_SONG: 'UPDATE_SONG',

    CLICK_PLAYLIST: 'CLICK_PLAYLIST',
    CLICK_TRACK: 'CLICK_TRACK',

    SEARCH_TRACK: 'SEARCH_TRACK',
    LINK_TRACK: 'LINK_TRACK'
  },

  PayloadSources: {
    SERVER_ACTION: 'SERVER_ACTION',
    VIEW_ACTION: 'VIEW_ACTION'
  }
};